version: "3"
services:
  php:
    build: .
    ports:
      - 80:80
    environment:
      - DB_HOST=mysql
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mention_history
    # (1) MySQL 8でデフォルト値が変更になり、PDOがまだ対応していないオプションを戻す
    #     https://www.php.net/manual/ja/ref.pdo-mysql.php
    # https://hub.docker.com/_/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --general-log=true
      - --general-log-file=/tmp/mysql-query.log
