version: "3"
services:
    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        # MySQL 8でデフォルト値が変更になり、PDOがまだ対応していないオプションを戻す
        # https://www.php.net/manual/ja/ref.pdo-mysql.php
        # https://hub.docker.com/_/mysql
        command: --default-authentication-plugin=mysql_native_password
